name: Deploy to Server

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          TARGET_DIR="/var/www/wordpress-main"
        elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
          TARGET_DIR="/var/www/wordpress-staging"
        else
          echo "Branch is not main or staging. Exiting."
          exit 1
        fi
        
        rsync -avz --delete --exclude '.git' ./ $SSH_USER@$SSH_HOST:$TARGET_DIR

        ssh $SSH_USER@$SSH_HOST "sudo chown -R www-data:www-data $TARGET_DIR && sudo service apache2 reload"
